# Generated by Django 4.2.9 on 2025-12-05 02:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0001_initial'),
        ('classes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PricePolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='策略名称')),
                ('billing_type', models.CharField(choices=[('session_card', '次卡'), ('monthly', '月卡'), ('semester', '学期制'), ('hourly', '按课时')], max_length=20, verbose_name='计费模式')),
                ('sessions', models.IntegerField(blank=True, help_text='次卡模式', null=True, verbose_name='课次数量')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='价格')),
                ('unit_price', models.DecimalField(decimal_places=2, help_text='单课时价格', max_digits=10, verbose_name='单价')),
                ('discount', models.DecimalField(decimal_places=2, default=1.0, help_text='1.00表示无折扣，0.8表示8折', max_digits=3, verbose_name='折扣')),
                ('validity_days', models.IntegerField(blank=True, null=True, verbose_name='有效期（天）')),
                ('description', models.TextField(blank=True, null=True, verbose_name='说明')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '价格策略',
                'verbose_name_plural': '价格策略',
                'db_table': 'price_policies',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_no', models.CharField(max_length=50, unique=True, verbose_name='订单号')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='应付金额')),
                ('actual_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='实付金额')),
                ('payment_method', models.CharField(choices=[('wechat', '微信支付'), ('alipay', '支付宝'), ('cash', '现金'), ('bank_transfer', '银行转账')], max_length=20, verbose_name='支付方式')),
                ('status', models.CharField(choices=[('pending', '待支付'), ('paid', '已支付'), ('refunding', '退款中'), ('refunded', '已退款'), ('failed', '支付失败')], default='pending', max_length=20, verbose_name='状态')),
                ('transaction_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='交易号')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='支付时间')),
                ('refunded_at', models.DateTimeField(blank=True, null=True, verbose_name='退款时间')),
                ('refund_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='退款金额')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('enrollment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='classes.enrollment', verbose_name='关联报名')),
                ('price_policy', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='finance.pricepolicy', verbose_name='价格策略')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='students.student', verbose_name='学员')),
            ],
            options={
                'verbose_name': '支付记录',
                'verbose_name_plural': '支付记录',
                'db_table': 'payments',
                'ordering': ['-created_at'],
            },
        ),
    ]
