# Generated by Django 4.2.9 on 2025-12-05 02:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_no', models.CharField(max_length=20, unique=True, verbose_name='学号')),
                ('real_name', models.CharField(max_length=50, verbose_name='真实姓名')),
                ('nickname', models.CharField(blank=True, max_length=50, null=True, verbose_name='昵称')),
                ('status', models.CharField(choices=[('active', '在读'), ('suspended', '休学'), ('graduated', '结业'), ('dropped', '退学')], default='active', max_length=20, verbose_name='学籍状态')),
                ('enrollment_date', models.DateField(auto_now_add=True, verbose_name='入学日期')),
                ('graduation_date', models.DateField(blank=True, null=True, verbose_name='结业日期')),
                ('guardian_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='监护人姓名')),
                ('guardian_phone', models.CharField(blank=True, max_length=11, null=True, verbose_name='监护人电话')),
                ('guardian_relation', models.CharField(blank=True, max_length=20, null=True, verbose_name='监护人关系')),
                ('health_info', models.TextField(blank=True, help_text='过敏史、既往病史等', null=True, verbose_name='健康信息')),
                ('special_notes', models.TextField(blank=True, null=True, verbose_name='特殊说明')),
                ('total_classes', models.IntegerField(default=0, verbose_name='总课时')),
                ('remaining_classes', models.IntegerField(default=0, verbose_name='剩余课时')),
                ('total_spent', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='累计消费')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL, verbose_name='关联用户')),
            ],
            options={
                'verbose_name': '学员',
                'verbose_name_plural': '学员',
                'db_table': 'students',
                'ordering': ['-created_at'],
            },
        ),
    ]
