# Generated by Django 4.2.9 on 2025-12-05 02:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0001_initial'),
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='教室名称')),
                ('capacity', models.IntegerField(verbose_name='容纳人数')),
                ('location', models.CharField(max_length=100, verbose_name='位置')),
                ('equipment', models.TextField(blank=True, null=True, verbose_name='设备')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否可用')),
            ],
            options={
                'verbose_name': '教室',
                'verbose_name_plural': '教室',
                'db_table': 'classrooms',
            },
        ),
        migrations.CreateModel(
            name='ClassType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='班型名称')),
                ('level', models.CharField(choices=[('beginner', '初级'), ('intermediate', '中级'), ('advanced', '高级'), ('professional', '专业')], max_length=20, verbose_name='级别')),
                ('age_range', models.CharField(help_text='如：4-6岁', max_length=50, verbose_name='适龄范围')),
                ('duration_minutes', models.IntegerField(default=60, verbose_name='单次课时长（分钟）')),
                ('max_students', models.IntegerField(default=20, verbose_name='最大人数')),
                ('description', models.TextField(blank=True, null=True, verbose_name='课程简介')),
                ('syllabus', models.TextField(blank=True, null=True, verbose_name='教学大纲')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='class_types/', verbose_name='封面图')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('sort_order', models.IntegerField(default=0, verbose_name='排序')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '班型',
                'verbose_name_plural': '班型',
                'db_table': 'class_types',
                'ordering': ['sort_order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='课程名称')),
                ('term', models.CharField(help_text='如：第1期', max_length=50, verbose_name='期次')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('enrolling', '招生中'), ('ongoing', '进行中'), ('completed', '已结束'), ('cancelled', '已取消')], default='draft', max_length=20, verbose_name='状态')),
                ('start_date', models.DateField(verbose_name='开课日期')),
                ('end_date', models.DateField(verbose_name='结课日期')),
                ('total_sessions', models.IntegerField(default=12, verbose_name='总课次')),
                ('enrolled_count', models.IntegerField(default=0, verbose_name='已报名人数')),
                ('max_students', models.IntegerField(default=20, verbose_name='招生名额')),
                ('is_open_enrollment', models.BooleanField(default=True, verbose_name='是否开放报名')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('class_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='classes.classtype', verbose_name='班型')),
                ('teacher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='teachers.teacher', verbose_name='授课教师')),
            ],
            options={
                'verbose_name': '课程',
                'verbose_name_plural': '课程',
                'db_table': 'courses',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DanceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='舞种名称')),
                ('description', models.TextField(blank=True, null=True, verbose_name='描述')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='dance_types/', verbose_name='图标')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
            ],
            options={
                'verbose_name': '舞种分类',
                'verbose_name_plural': '舞种分类',
                'db_table': 'dance_types',
            },
        ),
        migrations.AddField(
            model_name='classtype',
            name='dance_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='classes.dancetype', verbose_name='舞种'),
        ),
        migrations.CreateModel(
            name='ClassSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_no', models.IntegerField(verbose_name='第几课次')),
                ('start_time', models.DateTimeField(verbose_name='开始时间')),
                ('end_time', models.DateTimeField(verbose_name='结束时间')),
                ('status', models.CharField(choices=[('scheduled', '正常'), ('rescheduled', '已调课'), ('cancelled', '已取消')], default='scheduled', max_length=20, verbose_name='状态')),
                ('actual_students', models.IntegerField(default=0, verbose_name='实际出勤')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='classes.classroom', verbose_name='教室')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='classes.course', verbose_name='课程')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='teachers.teacher', verbose_name='授课教师')),
            ],
            options={
                'verbose_name': '排课',
                'verbose_name_plural': '排课',
                'db_table': 'class_schedules',
                'ordering': ['start_time'],
            },
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrollment_date', models.DateTimeField(auto_now_add=True, verbose_name='报名时间')),
                ('status', models.CharField(choices=[('pending', '待支付'), ('paid', '已支付'), ('refunding', '退款中'), ('refunded', '已退款'), ('cancelled', '已取消')], default='pending', max_length=20, verbose_name='状态')),
                ('source', models.CharField(default='线上', help_text='线上/线下/电话等', max_length=50, verbose_name='报名渠道')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='classes.course', verbose_name='课程')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='students.student', verbose_name='学员')),
            ],
            options={
                'verbose_name': '报名记录',
                'verbose_name_plural': '报名记录',
                'db_table': 'enrollments',
                'ordering': ['-enrollment_date'],
                'unique_together': {('student', 'course')},
            },
        ),
    ]
