# Generated by Django 4.2.9 on 2025-12-05 02:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0001_initial'),
        ('classes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('present', '出勤'), ('absent', '缺勤'), ('leave', '请假'), ('late', '迟到')], max_length=20, verbose_name='考勤状态')),
                ('check_in_time', models.DateTimeField(blank=True, null=True, verbose_name='签到时间')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='classes.classschedule', verbose_name='排课')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.student', verbose_name='学员')),
            ],
            options={
                'verbose_name': '考勤记录',
                'verbose_name_plural': '考勤记录',
                'db_table': 'attendances',
                'ordering': ['-created_at'],
                'unique_together': {('schedule', 'student')},
            },
        ),
    ]
