# Generated by Django 4.2.9 on 2025-12-05 02:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_no', models.CharField(max_length=20, unique=True, verbose_name='教师编号')),
                ('real_name', models.CharField(max_length=50, verbose_name='真实姓名')),
                ('specialty', models.CharField(max_length=100, verbose_name='擅长舞种')),
                ('experience_years', models.IntegerField(default=0, verbose_name='教龄（年）')),
                ('status', models.CharField(choices=[('active', '在职'), ('leave', '请假'), ('resigned', '离职')], default='active', max_length=20, verbose_name='状态')),
                ('introduction', models.TextField(blank=True, null=True, verbose_name='个人简介')),
                ('achievements', models.TextField(blank=True, null=True, verbose_name='教学成果')),
                ('hourly_rate', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='课时费（元/课时）')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='teachers/', verbose_name='照片')),
                ('join_date', models.DateField(verbose_name='入职日期')),
                ('leave_date', models.DateField(blank=True, null=True, verbose_name='离职日期')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_profile', to=settings.AUTH_USER_MODEL, verbose_name='关联用户')),
            ],
            options={
                'verbose_name': '教师',
                'verbose_name_plural': '教师',
                'db_table': 'teachers',
                'ordering': ['-created_at'],
            },
        ),
    ]
