# Generated by Django 4.2.9 on 2025-12-05 02:25

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='标题')),
                ('category', models.CharField(choices=[('news', '新闻动态'), ('activity', '活动公告'), ('performance', '演出作品'), ('tutorial', '教学心得')], max_length=20, verbose_name='分类')),
                ('cover', models.ImageField(upload_to='articles/', verbose_name='封面图')),
                ('summary', models.TextField(max_length=300, verbose_name='摘要')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='正文')),
                ('author', models.CharField(default='管理员', max_length=50, verbose_name='作者')),
                ('views', models.IntegerField(default=0, verbose_name='浏览量')),
                ('is_published', models.BooleanField(default=True, verbose_name='是否发布')),
                ('is_featured', models.BooleanField(default=False, verbose_name='是否推荐')),
                ('published_at', models.DateTimeField(auto_now_add=True, verbose_name='发布时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '文章',
                'verbose_name_plural': '文章',
                'db_table': 'articles',
                'ordering': ['-published_at'],
            },
        ),
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='标题')),
                ('image', models.ImageField(upload_to='banners/', verbose_name='图片')),
                ('link', models.URLField(blank=True, null=True, verbose_name='链接')),
                ('description', models.TextField(blank=True, null=True, verbose_name='描述')),
                ('sort_order', models.IntegerField(default=0, verbose_name='排序')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '轮播图',
                'verbose_name_plural': '轮播图',
                'db_table': 'banners',
                'ordering': ['sort_order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='姓名')),
                ('phone', models.CharField(max_length=11, verbose_name='联系电话')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='邮箱')),
                ('subject', models.CharField(max_length=100, verbose_name='主题')),
                ('message', models.TextField(verbose_name='留言内容')),
                ('is_replied', models.BooleanField(default=False, verbose_name='是否回复')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '联系留言',
                'verbose_name_plural': '联系留言',
                'db_table': 'contacts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='标题')),
                ('image', models.ImageField(upload_to='gallery/', verbose_name='图片')),
                ('description', models.TextField(blank=True, null=True, verbose_name='描述')),
                ('sort_order', models.IntegerField(default=0, verbose_name='排序')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否显示')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '作品相册',
                'verbose_name_plural': '作品相册',
                'db_table': 'gallery',
                'ordering': ['sort_order', '-created_at'],
            },
        ),
    ]
