# Generated by Django 4.2.9 on 2025-12-05 02:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlipayConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_id', models.CharField(max_length=64, verbose_name='App ID')),
                ('private_key', models.TextField(verbose_name='商户私钥')),
                ('alipay_public_key', models.TextField(verbose_name='支付宝公钥')),
                ('notify_url', models.URLField(blank=True, verbose_name='异步通知地址')),
                ('return_url', models.URLField(blank=True, verbose_name='同步跳转地址')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '支付宝配置',
                'verbose_name_plural': '支付宝配置',
            },
        ),
        migrations.CreateModel(
            name='HuPiPayConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_id', models.CharField(max_length=64, verbose_name='App ID')),
                ('app_secret', models.CharField(max_length=128, verbose_name='App Secret')),
                ('notify_url', models.URLField(blank=True, verbose_name='异步通知地址')),
                ('return_url', models.URLField(blank=True, verbose_name='同步跳转地址')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '虎皮椒支付配置',
                'verbose_name_plural': '虎皮椒支付配置',
            },
        ),
        migrations.CreateModel(
            name='WeChatPayConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_id', models.CharField(max_length=64, verbose_name='App ID')),
                ('mch_id', models.CharField(max_length=32, verbose_name='商户号')),
                ('api_key', models.CharField(max_length=64, verbose_name='API密钥')),
                ('cert_path', models.CharField(blank=True, max_length=255, verbose_name='证书路径')),
                ('key_path', models.CharField(blank=True, max_length=255, verbose_name='密钥路径')),
                ('notify_url', models.URLField(blank=True, verbose_name='异步通知地址')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '微信支付配置',
                'verbose_name_plural': '微信支付配置',
            },
        ),
        migrations.CreateModel(
            name='PaymentRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_no', models.CharField(max_length=64, unique=True, verbose_name='订单号')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='金额')),
                ('payment_method', models.CharField(choices=[('alipay_web', '支付宝网页支付'), ('alipay_qr', '支付宝当面付'), ('wechat_pay', '微信支付'), ('hupi_pay', '虎皮椒支付')], max_length=20, verbose_name='支付方式')),
                ('status', models.CharField(choices=[('pending', '待支付'), ('paid', '已支付'), ('failed', '支付失败'), ('refunded', '已退款')], default='pending', max_length=20, verbose_name='状态')),
                ('transaction_id', models.CharField(blank=True, max_length=128, null=True, verbose_name='交易号')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='支付时间')),
                ('refunded_at', models.DateTimeField(blank=True, null=True, verbose_name='退款时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.student', verbose_name='学员')),
            ],
            options={
                'verbose_name': '支付记录',
                'verbose_name_plural': '支付记录',
                'ordering': ['-created_at'],
            },
        ),
    ]
